### PR TITLE
Workaround for WDT issues with HX711

### PR DESCRIPTION
**Pull request by Gulaschcowboy**
Workaround for http://www.esp8266.com/viewtopic.php?f=8&t=11958

### CODE REVIEW

**Comment by amotl** [comment]
Dear Alex,

thanks for sharing your improvements! We don't know what went wrong, but your original commit https://github.com/Gulaschcowboy/arduino/commit/4d431440c1e940427fe36dd5191ac0a1f8dd49a3 looks much more clean to us. We will just cherry-pick this one and close this PR if you don't mind.

However, we would like to keep up the GPL licensing of all the code in the whole repository, would you agree on that? I'm just mentioning this detail because we recognized the amendment into the CC BY-NC 4.0.

With kind regards,
Andreas.

**Comment by Gulaschcowboy** [comment]
Yes please do cherry picking. Somehow I mixed up my local repos as I am testing at the moment in platformio and Arduino IDE. So the license change was an accident

**Comment by Gulaschcowboy** [comment]
Hi Andreas,

actually I decided to do a rebase, because I learned that my wourkaround is actually the preferred solution.
I'll do a slight rewrite

**Comment by amotl** [comment]
Great, thanks!

**Pull request closed without merging**
